" ~/.vimrc — managed by dotfiles (source of truth: ~/.config/vim/.vimrc, symlinked here).
"
" Purpose: give classic vim the same seamless Ctrl+h/j/k/l navigation that tmux
" and Neovim already share, via christoomey/vim-tmux-navigator. The plugin is
" installed as a vim8 native package under
" ~/.vim/pack/plugins/start/vim-tmux-navigator (see install.sh: configure_vim).
"
" Do NOT edit this file for machine-local tweaks — it is a symlink into the repo.
" Put personal / per-machine vim settings in ~/.vimrc.local instead; it is sourced
" at the end below and is not tracked by the repo. When install.sh first runs on a
" machine that already had a ~/.vimrc, it copies that original into ~/.vimrc.local
" so your existing settings keep loading on top of this file.

set nocompatible

" Keep Vim's distributed sensible defaults (syntax on, filetype plugin indent on,
" incsearch, etc.). These normally auto-load ONLY when no user vimrc exists, so
" adding this file would silently drop them — source them back explicitly.
if filereadable($VIMRUNTIME . '/defaults.vim')
  source $VIMRUNTIME/defaults.vim
endif

" --- vim-tmux-navigator -------------------------------------------------------
" Disable the plugin's built-in mappings and define them explicitly, mirroring
" nvim/lua/config/keymaps.lua. tmux (.tmux.conf.local) forwards C-h/j/k/l into
" vim when it detects a vim process; TmuxNavigate* moves between vim splits and
" hands off to the neighbouring tmux pane when the cursor is at a split edge.
" (Mappings may reference the :TmuxNavigate* commands before the package loads —
" they are only resolved when the key is pressed, so ordering is fine.)
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-h> :<C-U>TmuxNavigateLeft<CR>
nnoremap <silent> <C-j> :<C-U>TmuxNavigateDown<CR>
nnoremap <silent> <C-k> :<C-U>TmuxNavigateUp<CR>
nnoremap <silent> <C-l> :<C-U>TmuxNavigateRight<CR>

" --- machine-local overrides --------------------------------------------------
" Loaded last so it wins over the defaults above (and preserves any pre-existing
" ~/.vimrc that install.sh migrated here).
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif
